version: "3"

services:

  client:
    container_name: videochat_client
    build: ../client_next
    env_file: ../client_next/.env.production.local
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=dddsqrt-videochat.ru
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dddsqrt-videochat.ru
      - LETSENCRYPT_EMAIL=metbezu@gmail.com
    ports:
      - "3000:3000"
    networks:
      - reverse-proxy

  backend:
    container_name: videochat_backend
    build: ../backend
    env_file: ../backend/.env
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=api.dddsqrt-videochat.ru
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.dddsqrt-videochat.ru
      - LETSENCRYPT_EMAIL=metbezu@gmail.com
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - reverse-proxy

  mongo:
    container_name: videochat_mongodb
    restart: unless-stopped
    image: mongo:4
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external: true

