version: "3"

services:

  client:
    container_name: videochat_client
    build: ../client_next
    env_file: ../client_next/.env.production.local
    restart: unless-stopped
    ports:
      - "3000:3000"

  backend:
    container_name: videochat_backend
    build: ../backend
    env_file: ../backend/.env
    restart: unless-stopped
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: videochat_mongodb
    restart: unless-stopped
    image: mongo:4

  nginx-proxy:
    container_name: videochat_nginx_proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

#  nginx:
#    container_name: videochat_nginx
#    image: nginx
#    restart: unless-stopped
#    volumes:
#      - ../client_next/nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"




#  livekit:
#    container_name: videochat_livekit
#    build: ../livekit
#    ports:
#      - "7880:7880"
#      - "7881:7881"
#      - "7882:7882/udp"
#      - "50000-60000:50000-60000"
