version: "3"

services:

  client:
    container_name: videochat_client
    build: ../client_next
    volumes:
      - ../client_next:/app
    env_file: ../client_next/.env.local
    ports:
      - "3000:3000"

  backend:
    container_name: videochat_backend
    build: ../backend
    env_file: ../backend/.env
    volumes:
      - ../backend:/app
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: videochat_mongodb
    image: mongo:4


#  livekit:
#    container_name: videochat_livekit
#    build: ../livekit
#    ports:
#      - "7880:7880"
#      - "7881:7881"
#      - "7882:7882/udp"
#      - "50000-60000:50000-60000"
