version: "3"

services:

  client:
    container_name: videochat_client
    build: ../client_next
    volumes:
      - ../client_next:/app
    env_file: ../client_next/.env.development.local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dddsqrt-videochat.ru
      - LETSENCRYPT_EMAIL=metbezu@gmail.com
    ports:
      - "3000:3000"
    networks:
      - reverse-proxy

  backend:
    container_name: videochat_backend
    build: ../backend
    env_file: ../backend/.env
    volumes:
      - ../backend:/app
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - reverse-proxy

  mongo:
    container_name: videochat_mongodb
    image: mongo:4
    networks:
      - reverse-proxy



networks:
  reverse-proxy:
    external: true

