name: videochat workflow
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOY_SSH_HOST}}
          username: ${{secrets.DEPLOY_USERNAME}}
          key: ${{secrets.DEPLOY_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo "MOVING TO PROJECT DIRECTORY"
            cd ${{secrets.DEPLOY_WORKDIR}}
            echo "PULLING REPO CODE"
            git pull
            echo "MOVING TO DEPLOY DIR"
            cd deploy/
            docker compose -f docker-compose.prod.yaml up -d --force-recreate --build
            docker ps
            docker image prune -f
            docker volume prune -f
            docker builder prune -f
