name: videochat workflow
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOY_SSH_HOST}}
          username: ${{secrets.DEPLOY_USERNAME}}
          key: ${{secrets.DEPLOY_SSH_KEY}}
          port: 22
          script: |
            echo "MOVING TO PROJECT DIRECTORY"
            cd ${{secrets.DEPLOY_WORKDIR}}
            echo "PULLING REPO CODE"
            git pull
            echo "MOVING TO DEPLOY DIR"
            cd deploy/
            echo "STOP CONTAINERS"
            docker compose -f docker-compose.prod.yaml down
            echo "BUILDING IMAGES"
            docker compose -f docker-compose.prod.yaml build
            echo "STARTING CONTAINERS"
            docker compose -f docker-compose.prod.yaml up -d
            docker ps
